### ISSUE TITLE
Cyclical `always` transitions result in "Maximum callstack exceeded" error

### ISSUE THREAD

**Issue by Silverwolf90** [statelyai/xstate-vscode#22]
[This codesandbox includes a 2 state example.](https://codesandbox.io/s/eager-scott-edecu?file=/src/index.js:0-565) I've also experienced the same behavior with 3 states so assume it's related any cycle from `always` transitions.

Additionally, the inspector doesn't render anything when this cycle is present. But after commenting an `always` transition in the cycle, it renders correctly.

This renders correctly in the visualizer (independent of the vscode extension) with no issues.

**Comment by wKovacs64** [comment]
Someone in Discord pointed out that inlining the guards makes the error go away. Unfortunately, doing that prevents you from using the visual editor.

**Comment by Andarist** [comment]
Huh, inlining a guard vs referencing a guard should definitely not result in such a behavior difference. This is definitely a bug - and most likely in XState itself

**Comment by wKovacs64** [comment]
> Huh, inlining a guard vs referencing a guard should definitely not result in such a behavior difference. This is definitely a bug - and most likely in XState itself

To be clear, the machine executes properly at runtime regardless of where the guard is defined. It seems the VSCode extension just can't handle cyclic `always` transitions and for some reason inlining the guard prevents the maximum callstack exceeded error (but inlining the guard might just be causing the extension to fail/abort parsing the machine before the error can happen?).

**Comment by mattpocock** [comment]
Found a fix for this. XState was erroring too soon when you didn't provide a guard that was checked as part of an initial state. So we extract a bunch of 'guards to mock' from the machine definition.

By default, we were setting these guards as `() => true`. But we don't need to. Setting them as `() => false` works.

**Comment by mattpocock** [comment]
(reopening pending @wKovacs64 feedback)

**Comment by wKovacs64** [comment]
For those following along at home, it worked!
