### ISSUE TITLE
Typegen file not created on Windows

### ISSUE THREAD

**Issue by wKovacs64** [statelyai/xstate-vscode#40]
VSCode developer log for "Window" shows the following when saving a machine:

`[2022-01-27 16:34:50.561] [renderer1] [error] UNKNOWN: unknown error, stat '\\c%3A\dev\project\src\index.ts': Error: UNKNOWN: unknown error, stat '\\c%3A\dev\project\src\index.ts'`

And no typegen file is created. Probably a path resolution thing?

**Comment by mattpocock** [comment]
OK, I know what's causing this, but need a bit of time to get set up on windows and fix it.

**Comment by mattpocock** [comment]
For context, I'm pretty sure it's this line of code:

https://github.com/statelyai/xstate-vscode/blob/master/client/src/typegenService.ts#L57

**Comment by batnyu** [comment]
Hello, 

I fixed the issue on Windows and made a pull request. #41 
Unfortunately, I don't have a Mac, so I was unable to test on macOs.
I hope it can help you!

Thanks!

**Comment by mattpocock** [comment]
Fixed in 1.5.7
