### ISSUE TITLE
Visual editor delete parts of machine definitions automatically

### ISSUE THREAD

**Issue by nightire** [statelyai/xstate-vscode#43]
Opening up the visual editor with one of my working machines will automatically delete some code. However, the corresponding visual element remains on the canvas, and by clicking this element is still located to the (deleted) lines.

![image](https://user-images.githubusercontent.com/1104018/151661213-cea61781-9df2-4011-a2bc-6e73b0fec7df.png)

**Comment by mattpocock** [comment]
Fixed in latest version
