### ISSUE TITLE
Typegen file not created on Linux

### ISSUE THREAD

**Issue by GuillaumeAmat** [statelyai/xstate-vscode#45]
On:
- Linux (non Flatpak)
- XState v4.29.0
- @xstate/react v2.0.0
- XState VSCode v1.4.1

... The Typegen file is not generated and the `tsTypes: {},` line has the following TS error:

```
Type '{}' is not assignable to type 'TypegenConstraint | undefined'.
  Property ''@@xstate/typegen'' is missing in type '{}' but required in type 'TypegenEnabled'.ts(2322)
```

I don't have any error in VS Code logs, as in https://github.com/statelyai/xstate-vscode/issues/40 though...

What could I give you to better investigate?

**Comment by mattpocock** [comment]
@GuillaumeAmat looks like you're using the old extension? Make sure you download this one:

https://marketplace.visualstudio.com/items?itemName=statelyai.stately-vscode

**Comment by GuillaumeAmat** [comment]
Oh! Thanks :pray:
