### ISSUE TITLE
The extension automatically removes .mjs files

### ISSUE THREAD

**Issue by mtulp** [statelyai/xstate-vscode#49]
Files with a .mjs extension are automatically removed by the VsCode extension.
(Using the .js extension works fine. )

![xstate-vscode- mjs-remove](https://user-images.githubusercontent.com/53967102/152902755-416d2dde-ac41-41cb-8a68-5ae5a658cabf.gif)

**Comment by mattpocock** [comment]
This is wild. What on earth

**Comment by mattpocock** [comment]
Fixed in latest version

**Comment by mtulp** [comment]
I have tested it and it is now working properly. Thanks for the super fast response.
