### ISSUE TITLE
Bug: Typegen and NextJS pages

### ISSUE THREAD

**Issue by farskid** [statelyai/xstate-vscode#61]
When working with Typegen in the context of a NodeJS page, if any statechart is detected inside any pages in a NextJS application, Typegen will generate a new Typegen file under `page` directory which leads NextJS to treat it as a new page.

**Comment by mattpocock** [comment]
There's always this option:

https://nextjs.org/docs/api-reference/next.config.js/custom-page-extensions#including-non-page-files-in-the-pages-directory

**Comment by farskid** [comment]
That works.
