### ISSUE TITLE
Visualizer does not render delay arrays

### ISSUE THREAD

**Issue by mdpratt** [statelyai/xstate-vscode#64]
Machines that define an array for the `after` attribute do not correctly rendering the node.

Code: https://stately.ai/viz/29788792-45db-4927-9d66-590e9ecbbf65

```javascript
const example = createMachine({
  states: {
    idle: {
      after: [
        {
          delay: 1000,
          target: 'pending',
        },
      ],
    },
    pending: {},
  },
});
```

**Expected:**
![image](https://user-images.githubusercontent.com/982135/155036145-e19edd22-b94d-485b-947d-ef1e58d8998b.png)

**Actual:**
![image](https://user-images.githubusercontent.com/982135/155036098-1aa6b97c-7458-4ec6-956d-0c62012a5858.png)

**Comment by mdpratt** [comment]
It looks like `after` arrays are generally not being handled correctly. Defining a guard (eg. `after: [{ delay: settings.paginationDelay ?? 100, target: 'pending', cond: 'isPaginationAutomatic' }]` will cause the the TypeGen to fail with the following error messages:

Typescript will fail:
> Object literal may only specify known properties, and 'isPaginationAutomatic' does not exist in type 'MachineOptionsGuards<{ ...snip...}>

XState VSCode extension will warn:
> isPaginationAutomatic is never used in the machine definition

**Comment by mdpratt** [comment]
Is the visualization and typegen related to the same flaw? If not, I'd recommend reopening this issue.

**Comment by mattpocock** [comment]
Yes, it is - it's a parsing issue
